name: sh23
dependencies:
  - python=3.11
  - pip
  - jupyter
  - pip:
    - yfinance
    - matplotlib
    - flask
    - flask-cors
    - python-dotenv
    - pymongo
    - gnews
    - newspaper3k
    - nltk
    - Pillow
